### ISSUE TITLE
macOS - ld: library not found for -levent

### ISSUE THREAD

**Issue by joelcnz** [rejectedsoftware/vibenews#36]
This is the error I get when it tries to run.

**Comment by s-ludwig** [comment]
Do you have libevent installed? vibe.d currently still needs it as its event loop (Instructions using Homebrew: https://github.com/rejectedsoftware/vibe.d/#additional-setup-on-mac-using-brew)

**Comment by joelcnz** [comment]
Now I get:
ld: library not found for -lssl

What do I put for that?

**Comment by s-ludwig** [comment]
Hm, that's OpenSSL. I thought that this would  be available by default, but maybe it's actually necessary to install Xcode. Using brew should be fine, too, though. Which OS X/macOS version do you have and do you have Xcode installed? Would be good to extend the instructions accordingly.

**Comment by joelcnz** [comment]
macOS 10.12

I have the latest Xcode installed, (I think DMD compiler needs it).

It says that I've already installed OpenSSL with home brew?!

**Comment by s-ludwig** [comment]
I had to repair/reinstall Homebrew after the upgrade to 10.12. Libevent also worked after that, but I had to add a workaround for -lssl, because Homebrew doesn't create the symlinks for system-wide installation for it anymore. It should work now when using the latest vibe.d master (will commit a dependency update for vibenews later this week).

**Comment by joelcnz** [comment]
Thanks s-ludwig.

**Comment by s-ludwig** [comment]
0.7.3 has been tagged now.
